--TB_CODE 공용코드 마스터 테이블
insert into TB_CODE (CODE_ID, CODE_NAME, DESCRIPTION)
             VALUES ('OPERATOR', '운영기관', '전기차 충전소 운영기관(사업자)의 공용코드입니다' );
insert into TB_CODE (CODE_ID, CODE_NAME, DESCRIPTION)
             VALUES ('SPOT', '장소분류', '주변 편의시설의 종류를 설정하는 코드입니다' );
insert into TB_CODE (CODE_ID, CODE_NAME, DESCRIPTION)
             VALUES ('FAVOR', '즐겨찾기 대상 구분', '사용자가 선택한 즐겨찾기 대상을 구분하는 코드입니다' );
insert into TB_CODE (CODE_ID, CODE_NAME, DESCRIPTION)
             VALUES ('RECENT_TYPE', '검색기록 타입', '검색 히스토리의 종류를 구분하는 코드입니다(ROUTE,KEYWORD)' );
insert into TB_CODE (CODE_ID, CODE_NAME, DESCRIPTION)
             VALUES ('REPORT', '신고유형', '충전소 신고 유형을 결정하는 코드입니다' );
insert into TB_CODE (CODE_ID, CODE_NAME, DESCRIPTION)
             VALUES ('CHARGER_TYPE', '충전기 타입', '충전기 타입별 코드입니다' );


--TB_CODE_D 공용코드 디테일 테이블

--OPERATOR 하위코드

INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('AC', 'OPERATOR', '아우토크립트');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('AH', 'OPERATOR', '아하');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('AL', 'OPERATOR', '아론');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('AM', 'OPERATOR', '아마노코리아');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('AP', 'OPERATOR', '애플망고');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('BA', 'OPERATOR', '부안군');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('BE', 'OPERATOR', '브라이트에너지파트너스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('BG', 'OPERATOR', '비긴스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('BK', 'OPERATOR', '비케이에너지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('BN', 'OPERATOR', '블루네트웍스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('BP', 'OPERATOR', '차밥스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('BS', 'OPERATOR', '보스시큐리티');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('BT', 'OPERATOR', '보타리에너지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CA', 'OPERATOR', '씨에스테크놀로지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CB', 'OPERATOR', '참빛이브이씨');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CC', 'OPERATOR', '코콤');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CG', 'OPERATOR', '서울씨엔지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CH', 'OPERATOR', '채움모빌리티');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CI', 'OPERATOR', '쿨사인');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CN', 'OPERATOR', '에바씨엔피');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CO', 'OPERATOR', '한전케이디엔');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CP', 'OPERATOR', '캐스트프로');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CR', 'OPERATOR', '크로커스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CS', 'OPERATOR', '한국EV충전서비스센터');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CT', 'OPERATOR', '씨티카');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CU', 'OPERATOR', '씨어스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CV', 'OPERATOR', '채비');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('DE', 'OPERATOR', '대구공공시설관리공단');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('DG', 'OPERATOR', '대구시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('DL', 'OPERATOR', '딜라이브');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('DO', 'OPERATOR', '대한송유관공사');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('DP', 'OPERATOR', '대유플러스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('DR', 'OPERATOR', '두루스코이브이');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('DS', 'OPERATOR', '대선');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('DY', 'OPERATOR', '동양이엔피');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('E0', 'OPERATOR', '에너지플러스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EA', 'OPERATOR', '에바');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EB', 'OPERATOR', '일렉트리');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EC', 'OPERATOR', '이지차저');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EE', 'OPERATOR', '이마트');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EG', 'OPERATOR', '에너지파트너즈');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EH', 'OPERATOR', '이앤에이치에너지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EK', 'OPERATOR', '이노케이텍');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EL', 'OPERATOR', '엔라이튼');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EM', 'OPERATOR', 'evmost');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EN', 'OPERATOR', '이엔');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EO', 'OPERATOR', 'E1');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EP', 'OPERATOR', '이카플러그');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('ER', 'OPERATOR', '이엘일렉트릭');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('ES', 'OPERATOR', '이테스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('ET', 'OPERATOR', '이씨티');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EV', 'OPERATOR', '에버온');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('EZ', 'OPERATOR', '차지인');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('FE', 'OPERATOR', '에프이씨');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('FT', 'OPERATOR', '포티투닷');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('G1', 'OPERATOR', '광주시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('G2', 'OPERATOR', '광주시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('GD', 'OPERATOR', '그린도트');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('GE', 'OPERATOR', '그린전력');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('GG', 'OPERATOR', '강진군');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('GN', 'OPERATOR', '지에스커넥트');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('GO', 'OPERATOR', '유한회사 골드에너지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('GP', 'OPERATOR', '군포시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('GR', 'OPERATOR', '그리드위즈');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('GS', 'OPERATOR', 'GS칼텍스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HB', 'OPERATOR', '에이치엘비생명과학');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HD', 'OPERATOR', '현대자동차');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HE', 'OPERATOR', '한국전기차충전서비스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HL', 'OPERATOR', '에이치엘비일렉');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HM', 'OPERATOR', '휴맥스이브이');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HP', 'OPERATOR', '해피차지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HR', 'OPERATOR', '한국홈충전');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HS', 'OPERATOR', '홈앤서비스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HW', 'OPERATOR', '한화솔루션');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('HY', 'OPERATOR', '현대엔지니어링');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('IC', 'OPERATOR', '인천국제공항공사');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('IK', 'OPERATOR', '익산시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('IM', 'OPERATOR', '아이마켓코리아');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('IN', 'OPERATOR', '신세계아이앤씨');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('IO', 'OPERATOR', '아이온커뮤니케이션즈');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('IV', 'OPERATOR', '인큐버스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JA', 'OPERATOR', '이브이시스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JC', 'OPERATOR', '제주에너지공사');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JD', 'OPERATOR', '제주도청');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JE', 'OPERATOR', '제주전기자동차서비스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JH', 'OPERATOR', '종하아이앤씨');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JJ', 'OPERATOR', '전주시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JN', 'OPERATOR', '제이앤씨플랜');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JT', 'OPERATOR', '제주테크노파크');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('JU', 'OPERATOR', '정읍시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KA', 'OPERATOR', '기아자동차');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KC', 'OPERATOR', '한국컴퓨터');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KE', 'OPERATOR', '한국전기차인프라기술');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KG', 'OPERATOR', 'KH에너지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KH', 'OPERATOR', '김해시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KI', 'OPERATOR', '기아자동차');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KJ', 'OPERATOR', '순천시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KL', 'OPERATOR', '클린일렉스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KM', 'OPERATOR', '카카오모빌리티');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KN', 'OPERATOR', '한국환경공단');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KO', 'OPERATOR', '이브이파트너스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KP', 'OPERATOR', '한국전력');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KR', 'OPERATOR', '이브이씨코리아');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KS', 'OPERATOR', '한국전기차솔루션');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KT', 'OPERATOR', '케이티');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('KU', 'OPERATOR', '한국충전연합');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('L3', 'OPERATOR', '엘쓰리일렉트릭파워');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('LC', 'OPERATOR', '롯데건설');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('LD', 'OPERATOR', '롯데이노베이트');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('LH', 'OPERATOR', 'LG유플러스 볼트업(플러그인)');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('LI', 'OPERATOR', '엘에스이링크');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('LT', 'OPERATOR', '광성계측기');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('LU', 'OPERATOR', 'LG유플러스 볼트업');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('MA', 'OPERATOR', '맥플러스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('ME', 'OPERATOR', '환경부');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('MO', 'OPERATOR', '매니지온');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('MR', 'OPERATOR', '미래씨앤엘');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('MS', 'OPERATOR', '미래에스디');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('MT', 'OPERATOR', '모던텍');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('MV', 'OPERATOR', '메가볼트');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('NB', 'OPERATOR', '엔비플러스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('NE', 'OPERATOR', '에너넷');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('NH', 'OPERATOR', '농협경제지주 신재생에너지센터');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('NJ', 'OPERATOR', '나주시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('NN', 'OPERATOR', '이브이네스트');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('NS', 'OPERATOR', '뉴텍솔루션');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('NT', 'OPERATOR', '한국전자금융');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('NX', 'OPERATOR', '넥씽');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('OB', 'OPERATOR', '현대오일뱅크');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PA', 'OPERATOR', '이브이페이');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PC', 'OPERATOR', '파킹클라우드');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PE', 'OPERATOR', '피앤이시스템즈');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PI', 'OPERATOR', 'GS차지비');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PK', 'OPERATOR', '펌프킨');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PL', 'OPERATOR', '플러그링크');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PM', 'OPERATOR', '피라인모터스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PS', 'OPERATOR', '이브이파킹서비스');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('PW', 'OPERATOR', '파워큐브');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('RE', 'OPERATOR', '레드이엔지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('RS', 'OPERATOR', '리셀파워');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('S1', 'OPERATOR', '에스이피');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SA', 'OPERATOR', '설악에너텍');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SB', 'OPERATOR', '소프트베리');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SC', 'OPERATOR', '삼척시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SD', 'OPERATOR', '스칼라데이터');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SE', 'OPERATOR', '서울시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SF', 'OPERATOR', '스타코프');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SG', 'OPERATOR', 'SK시그넷');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SH', 'OPERATOR', '에스에이치에너지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SJ', 'OPERATOR', '세종시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SK', 'OPERATOR', 'SK에너지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SL', 'OPERATOR', '에스에스기전');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SM', 'OPERATOR', '성민기업');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SN', 'OPERATOR', '서울에너지공사');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SO', 'OPERATOR', '선광시스템');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SP', 'OPERATOR', '스마트포트테크놀로지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SR', 'OPERATOR', 'SK렌터카');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SS', 'OPERATOR', '투이스이브이씨');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('ST', 'OPERATOR', 'SK일렉링크');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SU', 'OPERATOR', '순천시 체육시설관리소');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SZ', 'OPERATOR', 'SG생활안전');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TB', 'OPERATOR', '태백시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TD', 'OPERATOR', '타디스테크놀로지');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TE', 'OPERATOR', '테슬라');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TH', 'OPERATOR', '태현교통');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TL', 'OPERATOR', '티엘컴퍼니');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TM', 'OPERATOR', '티맵');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TR', 'OPERATOR', '한마음장애인복지회');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TS', 'OPERATOR', '태성콘텍');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TU', 'OPERATOR', '티비유');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('TV', 'OPERATOR', '아이토브');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('UN', 'OPERATOR', '유니이브이');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('UP', 'OPERATOR', '유플러스아이티');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('US', 'OPERATOR', '울산시');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('VT', 'OPERATOR', '볼타');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('WB', 'OPERATOR', '이브이루씨');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('YC', 'OPERATOR', '노란충전');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('YY', 'OPERATOR', '양양군');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('ZE', 'OPERATOR', '이브이모드코리아');


--CHARGER_TYPE

INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_01', 'CHARGER_TYPE', 'DC차데모');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_02', 'CHARGER_TYPE', 'AC완속');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_03', 'CHARGER_TYPE', 'DC차데모+AC3상');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_04', 'CHARGER_TYPE', 'DC콤보');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_05', 'CHARGER_TYPE', 'DC차데모+DC콤보');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_06', 'CHARGER_TYPE', 'DC차데모+AC3상+DC콤보');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_07', 'CHARGER_TYPE', 'AC3상');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_08', 'CHARGER_TYPE', 'DC콤보(완속)');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_09', 'CHARGER_TYPE', 'NACS');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('CHARGER_TYPE_10', 'CHARGER_TYPE', 'DC콤보+NACS');


--SPOT

INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SPOT_01', 'SPOT', '카페');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SPOT_02', 'SPOT', '식당');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('SPOT_03', 'SPOT', '편의점');


--FAVOR
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('FAVOR_01', 'FAVOR', 'ROUTE');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('FAVOR_02', 'FAVOR', 'STATION');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('FAVOR_03', 'FAVOR', 'ACCOMMODATION');

--RECENT_TYPE
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('RECENT_TYPE_01', 'RECENT_TYPE', 'ROUTE');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('RECENT_TYPE_02', 'RECENT_TYPE', 'KEYWORD');


--REPORT
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('REPORT_01', 'REPORT', '위치정보 오류');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('REPORT_02', 'REPORT', '충전기 작동불가');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('REPORT_03', 'REPORT', '세부정보 불일치');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('REPORT_04', 'REPORT', '충전소 존재하지 않음');
INSERT INTO TB_CODE_D (CODE_DETAIL_ID, CODE_ID, CODE_DETAIL_NAME) VALUES ('REPORT_05', 'REPORT', '기타');

